### ISSUE TITLE
docker-compose for build and run

### ISSUE THREAD

**Issue by ohaz** [erlangen-dev/coffee-caller#10]
Both our "steps" (e.g. desktop client, android client, etc.)  and our run steps (run backend) can be run with docker-compose. How do we handle this? Two different compose files? Can't use the same because people who just want to run the backend don't want to build all apps at the same time.

**Comment by mxwnk** [comment]
I would prefer to have one single compose file for the moment. You can use `docker-compose start {backend}` to start a single service.

**Comment by ohaz** [comment]
Yes you can do that, still I think it feels weird to have different "build only" and "build and run" steps in the same compose file. Especially if we need multiple running services for the backend at some point.

On the other hand: YAGNI, KISS. So let's keep one.
