### ISSUE TITLE
Backend HTTP Framework

### ISSUE THREAD

**Issue by mxwnk** [erlangen-dev/coffee-caller#16]
We need to decide on a backend http framework to implement our history route.

* https://www.npmjs.com/package/koa
** fast, out of the box async / await support
* https://expressjs.com/de/ 
** most popular framework, feels a bit rusty 

Any other suggestions?

**Comment by t-animal** [comment]
Why don't we just re-send the messages of the last n minutes on connect? Then we don't need a history route. I've added the timestamp to the messages already anyhow, because doing so in the solid.js frontend was kinda painful.

**Comment by mxwnk** [comment]
I like the idea :) Closed for now
